baseurl = "https://congatudo.cloud/"
contentdir    = "content"
staticdir     = "static"
layoutdir     = "layouts"
publishdir    = "public"
title         = "Congatudo.cloud"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true

[Params]
  subtitle = "Free your Conga vacuum cleaner!"
  logo = "freeconga.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = false

[Author]
  name = "Conga hacking community"
  github = "congatudo"
  telegram = "congatudo"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "blog/index.html"
    weight = 2

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 4

[[menu.main]]
    name = "Congas"
    url = "page/congas/"
    weight = 3
